#!/bin/bash

bat0=$(acpi -b | grep 'Battery 0' | grep -Eo '[0-9]{1,3}\%' | grep -Eo '[0-9]*')
bat1=$(acpi -b | grep 'Battery 1' | grep -Eo '[0-9]{1,3}\%' | grep -Eo '[0-9]*')

avg=$(expr $bat0 + $bat1)
avg=$(expr $avg / 2)

status0=$(acpi -b | grep 'Battery 0' | grep -Eo '[a-zA-Z]*,' | grep -Eo '[a-zA-Z]*')
status1=$(acpi -b | grep 'Battery 1' | grep -Eo '[a-zA-Z]*,' | grep -Eo '[a-zA-Z]*')

if [ "$status0" = "Charging" ] || [ "$status1" = "Charging" ]; then
    echo -e "\uf240: $avg%, charging"
else
    if [ "$status0" = "Discharging" ] || [ "$status1" = "Discharging" ]; then
        echo -e "\uf240: $avg%, dying"
    else
        echo -e "\uf240: 100%"
    fi
fi


