#!/bin/bash

amixer_out=$(amixer get Master | grep -Eo '[0-9]{1,3}%')
mute=$(amixer get Master | grep -Eo '\bon\b|\boff\b' | head --lines=1)

if [[ "$mute" == "off" ]]; then
    echo -e "\uf028: $amixer_out, muted"
else
    echo -e "\uf028: $amixer_out"
fi
