theme = "ayu_dark"

[editor]
bufferline = "always"
auto-pairs = false

[keys.normal]
C-e = "scroll_down"
C-y = "scroll_up"
C-h = "goto_previous_buffer"
C-l = "goto_next_buffer"
C-o = "file_picker_in_current_directory"
